Q1. What is Min-Max scaling, and how is it used in data preprocessing? Provide an example to illustrate its  application. 

### Answer

Min-Max scaling is a data procesing technique that scales the value of a feature to a fixed range usually between 0 and 1.it is useful when the features have different ranges but we want to normalize them into the same scale. the formula for min-max scaling is:

X_scaled  = (X - X_min)/X_min - X_max

where X is the original value, where as X_min and X_max are the minimum and maximum values of the feture.

suppose we have dataset with two features: age and income, age ranges from 0 to 100, and income ranges from 0 to 100,000. we want to scale both features between 0 and 100, we can do that using min-max scaling:

In [6]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

X= np.array([[20,22000],[30,30000],
             [40,50000],[50,72000]])
scaler = MinMaxScaler()

X_scaled = scaler.fit_transform(X)

print(X_scaled)

[[0.         0.        ]
 [0.33333333 0.16      ]
 [0.66666667 0.56      ]
 [1.         1.        ]]


Q2. What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling?  Provide an example to illustrate its application. 


### Answer

Unit Vector technique also known as Normalization is a data processing technique where we can scale the value of the feature between the fixed range between 0 and 1.It is similar to the min-max scaling but instead of scaling between the minimum and maximum, we can scale the values between the length of the feature vector.

for example:
 suppose we have a dataset with two features: age and income. Age ranges from 0 to 100, while income ranges from 0 to 100,000. We want to scale both features to the feature vector using Unit Vector technique. We can apply Unit Vector technique as follows:

In [3]:
from sklearn.preprocessing import Normalizer
import numpy as np
X= np.array([[25,50000],[30,45000],[35,70000],[40,10000]])

normalizer=Normalizer()
X_scaled = normalizer.fit_transform(X)
print(X_scaled)

[[4.99999938e-04 9.99999875e-01]
 [6.66666519e-04 9.99999778e-01]
 [4.99999938e-04 9.99999875e-01]
 [3.99996800e-03 9.99992000e-01]]


The difference between Min-Max scaling and Unit Vector technique is that Min-Max scaling scales the values of a feature to a fixed range between minimum and maximum, while Unit Vector technique scales the values of a feature to the length of the feature vector.

Q3. What is PCA (Principle Component Analysis), and how is it used in dimensionality reduction? Provide an  example to illustrate its application. 


### Answer

**Principal Component Analysis (PCA)** is a statistical technique used to reduce the dimensionality of a dataset while retaining as much of the original information as possible. It works by identifying the principal components of the data, which are linear combinations of the original features that capture the most variation in the data. PCA is useful when working with high-dimensional data, where it can be difficult to visualize and analyze the data.

PCA can be used for dimensionality reduction by projecting the data onto a lower-dimensional space while retaining as much of the original information as possible. The number of principal components to keep is determined by how much variance they explain in the data. The more principal components we keep, the more information we retain, but at the cost of increased complexity.

Here’s an example of how PCA can be used for dimensionality reduction:

Suppose we have a dataset with 3 features: height, weight, and shoe size. We want to reduce the dimensionality of this dataset to 2 dimensions using PCA. We can apply PCA as follows:

In [6]:
from sklearn.decomposition import PCA
import numpy as np

x = np.array([[4,15,6],[5,20,7],[10,28,15],[7,25,12]])
pca = PCA(n_components=2)

x_pca = pca.fit_transform(x)
print(x_pca)

[[-8.37909678 -1.01626273]
 [-3.69945892  1.19612575]
 [ 8.52445238 -0.69433632]
 [ 3.55410332  0.51447329]]


As you can see, we have reduced the dimensionality of our dataset from 3 to 2 while retaining most of the original information.

Q4. What is the relationship between PCA and Feature Extraction, and how can PCA be used for Feature  Extraction? Provide an example to illustrate this concept. 


### Answer

**Principal Component Analysis (PCA)** is a type of feature extraction technique that can be used to reduce the dimensionality of a dataset while retaining as much of the original information as possible. PCA works by identifying the principal components of the data, which are linear combinations of the original features that capture the most variation in the data.

PCA can be used for feature extraction by projecting the data onto a lower-dimensional space while retaining as much of the original information as possible. The number of principal components to keep is determined by how much variance they explain in the data. The more principal components we keep, the more information we retain, but at the cost of increased complexity.

PCA is often used as a preprocessing step for machine learning algorithms to reduce the dimensionality of high-dimensional datasets. By reducing the number of features, we can improve the performance of machine learning algorithms and reduce overfitting.

Here’s an example of how PCA can be used for feature extraction:

Suppose we have a dataset with 4 features: age, income, height, and weight. We want to reduce the dimensionality of this dataset to 2 dimensions using PCA. We can apply PCA as:

In [8]:
X = np.array([[25, 50000, 170, 70], [30, 60000, 175, 75], [35, 70000, 180, 80], [40, 80000, 185, 85]])

pca = PCA(n_components=2)
x_pca = pca.fit_transform(X)
print(x_pca)

[[-1.50000056e+04  1.40898261e-15]
 [-5.00000187e+03 -5.99080316e-16]
 [ 5.00000187e+03  5.99080316e-16]
 [ 1.50000056e+04  1.00959573e-15]]


As you can see, we have reduced the dimensionality of our dataset from 4 to 2 while retaining most of the original information.

Q5. You are working on a project to build a recommendation system for a food delivery service. The dataset  contains features such as price, rating, and delivery time. Explain how you would use Min-Max scaling to  preprocess the data.

### Answer

In the context of a food delivery service recommendation system, Min-Max scaling can be used to preprocess the data by scaling the values of each feature to a fixed range between 0 and 1. This is useful when the features have different ranges, and we want to normalize them to the same scale.

For example, suppose we have a dataset with three features: price, rating, and delivery time. Price ranges from 0 to 100, rating ranges from 0 to 5, and delivery time ranges from 0 to 60 minutes. We want to scale all three features to a range between 0 and 1. We can apply Min-Max scaling as follows:

In [9]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

X= np.array([[50,4,20],[75,5,40],[20,5,30],[90,5,40]])
scaler = MinMaxScaler()

x_scaled = scaler.fit_transform(X)
print(x_scaled)

[[0.42857143 0.         0.        ]
 [0.78571429 1.         1.        ]
 [0.         1.         0.5       ]
 [1.         1.         1.        ]]


Q6. You are working on a project to build a model to predict stock prices. The dataset contains many  features, such as company financial data and market trends. Explain how you would use PCA to reduce the  dimensionality of the dataset.

### Answer

In the context of a project to predict stock prices, Principal Component Analysis (PCA) can be used to reduce the dimensionality of the dataset by identifying the principal components of the data, which are linear combinations of the original features that capture the most variation in the data. By reducing the number of features, we can improve the performance of machine learning algorithms and reduce overfitting.

PCA works by projecting the data onto a lower-dimensional space while retaining as much of the original information as possible. The number of principal components to keep is determined by how much variance they explain in the data. The more principal components we keep, the more information we retain, but at the cost of increased complexity.

Here’s an example of how PCA can be used for dimensionality reduction in a stock price prediction project:

Suppose we have a dataset with 10 features: company financial data and market trends. We want to reduce the dimensionality of this dataset to 5 dimensions using PCA. We can apply PCA as follows:

In [10]:
X= np.random.rand(1000,10)

pca = PCA(n_components=5)
x_pca= pca.fit_transform(X)

print(x_pca)

[[-0.0786305   0.00681502 -0.1717246  -0.11972289  0.18456256]
 [ 0.22444989  0.25005096 -0.28678874 -0.25612216  0.3146473 ]
 [-0.39760426  0.16452989  0.01853192  0.35214628  0.12261278]
 ...
 [ 0.13856791 -0.06306234  0.06547262 -0.24364704  0.08825853]
 [ 0.16809991 -0.00943217 -0.37695786 -0.2179353   0.18228137]
 [ 0.01935798  0.54284706  0.11707303  0.05689358  0.30103826]]


Q7. For a dataset containing the following values: [1, 5, 10, 15, 20], perform Min-Max scaling to transform the  values to a range of -1 to 1

### Answer

In [15]:
from sklearn.preprocessing import MinMaxScaler 
import numpy as np

X=np.array([[1,5,10,15,20]])

new_min=-1
new_max= 1

old_min=np.min(X)
old_max=np.max(X)

X_scaled = ((X - old_min) / (old_max - old_min)) * (new_max - new_min) + new_min

print(X_scaled)


[[-1.         -0.57894737 -0.05263158  0.47368421  1.        ]]


Q8. For a dataset containing the following features: [height, weight, age, gender, blood pressure], perform  Feature Extraction using PCA. How many principal components would you choose to retain, and why? 


### Answer

In the context of a dataset containing the following features: [height, weight, age, gender, blood pressure], we can apply PCA as follows:

In [17]:
from sklearn.decomposition import PCA
import numpy as np

X= np.random.rand(1000,5)

pca = PCA()

# Fit and transform the data
X_pca = pca.fit_transform(X)

# Calculate the explained variance ratio for each principal component
explained_variance_ratio = pca.explained_variance_ratio_

print(explained_variance_ratio)

[0.22418512 0.20503565 0.19727443 0.1879835  0.1855213 ]
